# -*- coding: utf-8 -*-
"""Merge Code Document Analysis with mega File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-coZXrrsrGO4qxs8UHXT-fb2-VDDJvj
"""

import pandas as pd

df_main = pd.read_excel("/content/for stata MAR2025.xlsx")

df_main.head()

df1 = pd.read_excel("/content/Code Document Analysis Customer Privacy.xlsx")
df2 = pd.read_excel("/content/Normalized Code Document Analysis Customer Privacy.xlsx")
df3 = pd.read_excel("/content/Binarize CDA Customer Privacy.xlsx")
df4 = pd.read_excel("/content/Row Relative CDA.xlsx")

df1.head()

df2.head()

def clean_and_rename(df):
    # Rename Unnamed: 0 to deal_id if it exists
    if 'Unnamed: 0' in df.columns:
        df = df.rename(columns={'Unnamed: 0': 'dealid'})
    # Clean deal_id: keep only up to and including first 'T'
    df['dealid'] = df['dealid'].astype(str).str.extract(r'(^.*?T)')
    return df

df1 = clean_and_rename(df1)
df2 = clean_and_rename(df2)
df3 = clean_and_rename(df3)
df4 = clean_and_rename(df4)

df1.head()



df_main.dealid

df_main.columns

df_main.drop(['Data Analytics Skills (RR)', 'Product Enhancement (RR)',
       'Personalized Customer Experience (RR)',
       'Technological/Capability Improvements (RR)', 'New Market Access (RR)',
       'Product Innovation (RR)', 'Data Security (RR)',
       'Employee Productivity Improvements (RR)', 'Fraud Prevention (RR)',
       'Digital Customer Experience (RR)'], axis=1, inplace=True)

df_main.head()

df_main.columns

df_main.drop(['Data Analytics Skills (Norm)', 'Product Enhancement (Norm)',
       'Personalized Customer Experience (Norm)',
       'Technological/Capability Improvements (Norm)',
       'New Market Access (Norm)', 'Product Innovation (Norm)',
       'Data Security (Norm)', 'Employee Productivity Improvements (Norm)',
       'Fraud Prevention (Norm)', 'Digital Customer Experience (Norm)'], axis=1, inplace=True)

df_main.columns

df_main.drop(['Data Analytics Skills (Bin)', 'Product Enhancement (Bin)',
       'Personalized Customer Experience (Bin)',
       'Technological/Capability Improvements (Bin)',
       'New Market Access (Bin)', 'Product Innovation (Bin)',
       'Data Security (Bin)', 'Employee Productivity Improvements (Bin)',
       'Fraud Prevention (Bin)', 'Digital Customer Experience (Bin)'], axis=1, inplace=True)

df_main.columns

df_main.drop(['Data Analytics Skills (Abs)', 'Product Enhancement (Abs)',
       'Personalized Customer Experience (Abs)',
       'Technological/Capability Improvements (Abs)',
       'New Market Access (Abs)', 'Product Innovation (Abs)',
       'Data Security (Abs)', 'Employee Productivity Improvements (Abs)',
       'Fraud Prevention (Abs)', 'Digital Customer Experience (Abs)'], axis=1, inplace=True)

df_main.columns

df1.head()

merged = df_main.merge(df1, on='dealid', how='left', suffixes=('', '(abs)'))\
                .merge(df2, on='dealid', how='left', suffixes=('', '(norm)'))\
                .merge(df3, on='dealid', how='left', suffixes=('', '(bin)'))\
                .merge(df4, on='dealid', how='left', suffixes=('', '(rr)'))

merged.head()

merged.to_excel("Combined_Strata_file_with_CodeDocumentAnalysis_with_CustomerPrivacy.xlsx", index=False)

